### ISSUE TITLE
Add binaries to latest release

### ISSUE THREAD

**Issue by tdaede** [simoninns/SmallyMouse2#16]
v1.2 is missing a binary.

FWIW probably only the .hex or .bin files are enough for DFU purposes.

**Comment by simoninns** [comment]
I noticed that recently :)  I'm just running through some testing (and there are a couple more pending fixes) ready for a 1.3 release (1.2 had a couple of noticeable bugs for Atari and Amiga users).  

When I release 1.3 I will include the .hex and close this issue (just so I don't forget in the meantime).

Thanks for the report!

**Comment by pazuzu72** [comment]
Hi, is there any news on version 1.3? I need to make a couple for atari and amiga.

**Comment by simoninns** [comment]
V1.3 released including .hex firmware image
