### ISSUE TITLE
RMB will not work on A1200

### ISSUE THREAD

**Issue by kipper2k** [simoninns/SmallyMouse2#21]
Hi Simon, i just built the Smally mouse and programmed the 1.3 FW on it. It works great on the Amiga 500. I am now trying it on the Amiga 1200 and the RMB will not register, When i go back to the a500 all is fine. If i try a different mouse in the a1200 then the RMB works.  (the chip is from Digikey so i don't believe i have a bad chip)

 I did do some looking and found this info...

http://eab.abime.net/showthread.php?t=71558

 It appears more people are having the same issue. Is there anything that can be done to fix that.  Thanks Sinon.

UPDATE:  the RMB doesnt work in the Rev2B A1200 but does work in a Rev 1D, strange
Brian

**Comment by simoninns** [comment]
This issue has been seen previously and the root cause was always a faulty PAULA chip.  I don't have any Amigas to test against myself, but the issue and resolution were tracking in a previous issue report:

https://github.com/simoninns/SmallyMouse2/issues/6
