### ISSUE TITLE
Accept input from multiple USB mice

### ISSUE THREAD

**Issue by Mellified** [simoninns/SmallyMouse2#22]
I have my SmallyMouse2 connected to an Atari Jaguar via a DB9 to DB15 adapter. With the wireless USB dongle for my mouse attached directly to the SmallyMouse2 everything works as expected! However, when connecting through my USB KVM the SmallyMouse2 does not work. I assume this is because there are multiple USB devices connected: 2 mice and 2 keyboards. In Linux and Windows the default behavior when multiple USB HID mice are connected is to sum the inputs and move the cursor accordingly. I'd like to see SmallyMouse2 updated to do the same ideally.

**Comment by simoninns** [comment]
Unfortunately acting as a hub and supporting multiple device types is not really practical as the on-board processor doesn't have the support capabilities.  SmallyMouse2 only supports a single USB HID mouse device via the USB port.
