### ISSUE TITLE
Deluxe Galaga autopauses when SmallyMouse adapter plugged

### ISSUE THREAD

**Issue by GuerreroNinja** [simoninns/SmallyMouse2#24]
I have 2 A1200, one rev 2B and another rev 1D. Strangely, the 1D one is affected by the RMB bug (faulty paula?) while the 2B one works ok. Using the A1200 that RMB works, I tested several games and apps, and found Deluxe Galaga behaves strange when the SmallyMouse2 adapter is plugged in. In AGA version, it just pauses itself like pressing P or RMB when playing. In AGA ECS, game stutters and slows randomly.

I tested other mouse oriented games, like Dune 2, Elvira, Eye of the Beholder... work as intended.

Affected program: Deluxe Galaga v2.6 AGA - Deluxe Galaga v2.6 ECS
Bug: RMB press itself and pauses the game in AGA, in ECS version game slows down.

**Comment by simoninns** [comment]
If the USB->Mouse is working then this is 99.9% either a local fault with the Amiga (very likely) or a local fault with the SmallyMouse hardware (less likely).  Either way there is no way for me to reproduce or diagnose this issue.  So I will have to close.  Please generate a new report if you have any technical information or clues as to the behaviour you observed.
